#XCC=/home/amol/toolchains/gcc-5.3.1/gcc-linaro-5.3.1-2016.05-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc
#XCC=/home/amol/toolchains/gcc-linaro-5.4.1-2017.01-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc


XCC=/home/amol/buildroot_BBB/buildroot_sandbox4/buildroot-2016.11.1/output/host/usr/bin/arm-buildroot-linux-uclibcgnueabihf-gcc
SRC=hello_world.c


all: $(SRC)
	$(XCC) $(SRC)
